import { readFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import assert from 'node:assert/strict';
const { PGlite } = await import(pathToFileURL(process.argv[2]).href);
const db = new PGlite();
const admin = '00000000-0000-0000-0000-000000000001';
const customer = '00000000-0000-0000-0000-000000000002';
const sub = '00000000-0000-0000-0000-000000000003';
const receipt = '00000000-0000-0000-0000-000000000004';
await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role;
 CREATE SCHEMA auth; CREATE TABLE auth.users(id uuid PRIMARY KEY);
 CREATE TABLE public.users(id uuid PRIMARY KEY, role text);
 CREATE TABLE subscription_plans(plan_key text PRIMARY KEY, currency text);
 CREATE TABLE subscriptions(id uuid PRIMARY KEY, plan_key text, updated_at timestamptz);
 INSERT INTO auth.users VALUES('${admin}'),('${customer}');
 INSERT INTO public.users VALUES('${admin}','admin'),('${customer}','user');
 INSERT INTO subscription_plans VALUES('solo','INR');
 INSERT INTO subscriptions(id,plan_key) VALUES('${sub}','solo');`);
await db.exec(await readFile(new URL('../../supabase/migrations/20260919140000_manual_subscription_payments.sql', import.meta.url), 'utf8'));
const future = new Date(Date.now() + 30 * 86400000).toISOString();
const call = (who = admin, amount = 30000) => `SELECT record_manual_subscription_payment('${receipt}','${sub}','${who}',${amount},'UPI-123','${future}')`;
await assert.rejects(db.exec(call(customer)), /Admin access required/);
await db.exec(call());
await db.exec(call());
assert.equal((await db.query('SELECT count(*) AS n FROM manual_subscription_payments')).rows[0].n, 1);
const row = (await db.query('SELECT * FROM manual_subscription_payments')).rows[0];
assert.equal(row.recorded_by, admin);
assert.equal(row.amount, 30000);
assert.equal(row.currency, 'INR');
assert.equal(new Date((await db.query('SELECT manual_paid_until FROM subscriptions')).rows[0].manual_paid_until).toISOString(), future);
await assert.rejects(db.exec(call(admin, 999)), /different details/);
await db.exec('SET ROLE authenticated');
await assert.rejects(db.exec(call()), /permission denied/);
await assert.rejects(db.exec('SELECT * FROM manual_subscription_payments'), /permission denied/);
await db.close();
console.log('Manual payment SQL passed: admin enforcement, atomic access grant and audit record, duplicate retry handling, and RPC/table permissions.');
